### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by zhuguoliangAI** [nikini/ionic-gallery-modal#56]
i install the gallery-modal follow the readme.md, and when i start my demo, there is a error like this

Error: Uncaught (in promise): TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at HammerGesturesPlugin.isCustomEvent (http://localhost:8100/build/vendor.js:35509:55)
    at HammerGesturesPlugin.supports (http://localhost:8100/build/vendor.js:35467:75)
    at EventManager._findPluginFor (http://localhost:8100/build/vendor.js:34352:26)
    at EventManager.addEventListener (http://localhost:8100/build/vendor.js:34307:44)
    at DefaultDomRenderer2.listen (http://localhost:8100/build/vendor.js:34962:53)
    at DebugRenderer2.listen (http://localhost:8100/build/vendor.js:15477:30)
    at listenToElementOutputs (http://localhost:8100/build/vendor.js:10660:83)
    at createViewNodes (http://localhost:8100/build/vendor.js:13769:17)
    at createEmbeddedView (http://localhost:8100/build/vendor.js:13680:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15093:42)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:48522:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:48515:14)
    at http://localhost:8100/build/vendor.js:48562:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242

and my ionic info is like this:

![info](https://user-images.githubusercontent.com/35722591/37072444-8f636450-21fc-11e8-977a-f07971c90161.png)
and my code is so easy like this:
![code1](https://user-images.githubusercontent.com/35722591/37072553-13438674-21fd-11e8-9175-987243662f53.png)
![code2](https://user-images.githubusercontent.com/35722591/37072554-138b3212-21fd-11e8-9b45-333f04e61991.png)
![coode3](https://user-images.githubusercontent.com/35722591/37072555-13ce35e4-21fd-11e8-8897-b6d94f917b2c.png)
anybody meet this error?or can anybody help me? thank you very much

**Comment by zhuguoliangAI** [comment]
oooh, it's my problem,i solved myself。
